name: BookSystem
version: 1.1.0
api: 3.9.0
main: goldentouch74\BookSystem\Main
author: GoldenTouch74
depend: [PiggyCustomEnchants]
commands:
  ceshop:
    description: "Open CustomEnchants Shop"
